### ISSUE TITLE
DAWA widget resource hungry

### ISSUE THREAD

**Issue by compelling** [SDFIdk/dawa-autocomplete2#1]
We have investigated a possible bottleneck/performance issue regarding DAR DAWA calls.
You can do a maximum of 10 concurrent calls from a given IP according to the docs.
https://dawadocs.dataforsyningen.dk/dok/api/generelt#maxrequests
This could possibly cause issues when many users are using a system we're involved in.

The widget does a DAR DAWA call for every keypress instead of waiting for the user to pause the typing. For fast typing operators, this will give several DAR DAWA calls per second, so if perhaps just 3-4 concurrent users are searching for an address we would get the 429 error.

Given the constraints to concurrent calls from one IP, it might be a good idea to refactor this is the current implementation which is a bit resource hungry.

**Comment by Montago** [comment]
Not only concurrent calls - but several re-attemps are made. 

I know of 2 instances where this DAWA address lookup isn't working and in both cases, the API sends several 100 attemps to the DAWA API. 

Currently im visiting Bornfiber.dk doing an address lookup, and my network monitor in Dev Tools shows over 500 requests to DAWA...
