### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by trueninjaturtle** [SDFIdk/dawa-autocomplete2#11]
Hi,

Seems the package doesn't work anymore because of an expired SSL certificate of the baseUrl https://dawa.aws.dk/.

Can anyone look into this?

**Comment by iamfrank** [comment]
Hi @trueninjaturtle 

I've tried to recreate the bug in both Firefox, Chrome, and Safari on MacOS. Both by importing the script from NPM and just pulling the script from CDN. 

You might have been caught between SSL cert updates. Give it another try and reopen this issue if the problem persists.
I'm closing the issue for now.
