### ISSUE TITLE
Improved error handling if service unavailable

### ISSUE THREAD

**Issue by HenrikKorsgaardKnowit** [SDFIdk/dawa-autocomplete2#19]
If the api endpoint is unavailable (dawa.aws.dk), the current implementation will retry with a default delay at 500ms and write [an error to console. ](https://github.com/SDFIdk/dawa-autocomplete2/blob/2b680c84b6a01d001669cce9a33f2681384e1c16/src/autocomplete-controller.js#L125)

This makes it very difficult to handle errors (regardless of how stable Dawa autocomplete2 is). 

It would be nice with the ability to handle the potential connection error:
- Throw error
- Emit error event
- provide an optional errorHandler function (similar to selectInitial)

**Comment by DocDemar** [comment]
@HenrikKorsgaardKnowit  - we will not add any new features or improvements to autocomplete
gsearch is the new autocomplete 

if gsearch is lacking in features, perfomance or other issues - please let us know and we will fix it if we are able to to

have a nice weekend

**Comment by woutervanvliet** [comment]
@DocDemar That would have been very interesting information to have, especially before we started implementing dawa-autocomplete2 in our solution ;).

Perhaps the README file of the data-autocomplete2 repo can be updated to reflect this, just like the documentation found here: https://dawadocs.dataforsyningen.dk/dok/guides

**Comment by DocDemar** [comment]
sry for that - we weren't quit ready to push this recommendation
We will update the docs as soon as possible

**Comment by DocDemar** [comment]
Hi Henrik

DAWA-autocomplete2 will in time be replace (deprecated) by gsearch and gsearch-ui.

The timeline is not yet decided. We need input from you and other users as to what is missing in Gsearch in order to be able to make the switch fra Autocomplete to Gsearch.

It is neccesary to create a token at dataforsyningen.dk in order to use Gsearch
there is no change in terms of use.

We know that autocomplete is a blockbuster API and we will do our best to replace it with something as great as autocomplete.

Any specific input will be very valued in order for us to make Gsearch and Gsearch-iu as great as Autocomplete

**Comment by HenrikKorsgaardKnowit** [comment]
@DocDemar you are more than welcome to reach out when you need input. I'd be happy to review and give input for gsearch when you are ready.

**Comment by DocDemar** [comment]
Thanks - if you have any input we will be happy to recieve it now

**Comment by kropsi** [comment]
Hi @DocDemar,

Could you please clarify the reasoning behind creating a new GSearch-UI component? DAWA-autocomplete2 has proven to be a robust and effective solution that has consistently addressed our use cases over time.

Additionally, we have been extensively utilizing DAWA APIs, like https://api.dataforsyningen.dk/autocomplete, along with other DAWA endpoints, as reliable sources for Danish addresses and the associated information. Are these APIs also at risk of deprecation?

From your implementation of the Gsearch UI, which uses [GSearch](https://github.com/SDFIdk/gsearch ) endpoint https://api.dataforsyningen.dk/rest/gsearch/v2.0/, it appears to function quite differently by calling multiple resources at once, such as:  
`navngivenvej, husnummer, adresse, stednavn, kommune, region, retskreds, postnummer, opstillingskreds, sogn, politikreds, matrikel, matrikel_udgaaet`,  
and then combining the data on the frontend without an autocomplete feature. This approach seems more limited in functionality compared to the DAWA web services we are currently using.

Looking forward to your thoughts.

**Comment by HenrikKorsgaardKnowit** [comment]
Hi @DocDemar,

Is there an update on the roadmap for deprecating autocomplete2 and replacing it with gsearch?

Who within SDFIdk would be able to answer questions related to the roadmap? This is a critical dependency for a couple of projects of ours.

**Comment by iamfrank** [comment]
Hi @HenrikKorsgaardKnowit 
@DocDemar is on leave and will return in January. 
Until then, you can try reaching out to [these guys](https://www.klimadatastyrelsen.dk/om-os/organisation/forvaltningsdata) that have more say over the roadmap for DAWA and DAWA-autocomplete.

**Comment by MargitKildevang** [comment]
Hi @HenrikKorsgaardKnowit
If you have any questions regarding DAWA, please write to support@kds.dk
Plan for DAWA can be followed in the below page
https://dataforsyningen.dk/data/4924

**Comment by HenrikKorsgaardKnowit** [comment]
@MargitKildevang thank you for the link. It seems to describe the plan for DAWA and not this specific library.  I will write the folks at Support and the link @iamfrank sent.
